spring:
  application:
    name: consumer
  profiles:
    active: local

server:
  port: 3003

eureka:
  client:
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://eureka:1234@localhost:3000/eureka/

